services:
  node:
    image: opendigitaleducation/node:16-alpine
    working_dir: /home/node/app
    network_mode : host
    volumes:
      - ./:/home/node/app
      - ~/.npm:/.npm
      - ../ode-bootstrap:/home/node/ode-bootstrap