version: "2"
services:
  node:
    image: "opendigitaleducation/node:16-alpine"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - ~/.npm:/.npm
      - ../ode-bootstrap:/home/node/ode-bootstrap