services:
  node:
    image: "opendigitaleducation/node:18-alpine-pnpm"
    user: "node"
    working_dir: /home/node/app
    network_mode: host
    volumes:
      - ./:/home/node/app
      - ~/.pnpm:/.pnpm
      - ~/.npm:/.npm
      - ~/.cache:/.cache
      - ../ode-bootstrap:/home/node/ode-bootstrap
      - ~/.gitconfig:/home/node/.gitconfig
      - ../recette:/home/node/recette
